#!/usr/bin/env python3
"""Round-trip research harness for docxsphinx.

Invokes pandoc to reverse each ``.docx`` in an input directory to Markdown,
feeds that Markdown through ``docxsphinx``'s forward path, and then compares
the original OOXML against what docxsphinx produces. Differences in
paragraph styles, run styles, element tag distributions, and structural
counts are aggregated into a Markdown report that highlights where
docxsphinx's forward output diverges from idiomatic Word documents.

Usage (run inside the dev container — pandoc + docxsphinx must be on PATH):

    python tools/roundtrip.py <input_dir> <output_dir>

The input directory is searched flat for ``.docx`` files. For each one, a
per-document report is written to ``<output_dir>/<stem>.report.md``, and a
cross-corpus ``aggregate.report.md`` summarises patterns seen across the
whole input set.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
import zipfile
from collections import Counter
from pathlib import Path

from lxml import etree

WML_NS = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
W = '{' + WML_NS + '}'

_CONF_PY = """\
# Auto-generated by tools/roundtrip.py — minimal Sphinx config that runs
# the candidate Markdown through docxsphinx's forward path.
project = 'roundtrip'
version = '0.1'
release = '0.1'
language = 'en'
extensions = ['myst_parser', 'docxsphinx']
source_suffix = {'.md': 'markdown'}
master_doc = 'index'
myst_enable_extensions = [
    'colon_fence',
    'deflist',
    'strikethrough',
    'tasklist',
]
exclude_patterns = ['_build']
"""


# ---------------------------------------------------------------------------
# OOXML extraction + summarisation
# ---------------------------------------------------------------------------

def extract_document_xml(docx_path: Path) -> etree._Element:
    """Return the parsed ``word/document.xml`` root from a ``.docx`` file."""
    with zipfile.ZipFile(docx_path) as zf:
        xml = zf.read('word/document.xml')
    return etree.fromstring(xml)


_SUMMARY_RUN_FLAGS = {'b', 'i', 'u', 'strike', 'vertAlign', 'color'}


def summarise_tree(root: etree._Element) -> dict:
    """Reduce an OOXML document tree to the coarse shape features we care
    about: paragraph/run/table counts, the distribution of paragraph and
    run style names, and a full per-tag element census."""
    summary: dict = {
        'paragraph_count': 0,
        'run_count': 0,
        'table_count': 0,
        'hyperlink_count': 0,
        'drawing_count': 0,
        'numPr_presence': 0,
        'pStyle_counts': Counter(),
        'rStyle_counts': Counter(),
        'rPr_flags': Counter(),
        'element_tags': Counter(),
    }
    val_attr = W + 'val'
    for el in root.iter():
        tag = el.tag
        if not isinstance(tag, str) or not tag.startswith(W):
            continue
        local = tag[len(W):]
        summary['element_tags'][local] += 1
        if local == 'p':
            summary['paragraph_count'] += 1
        elif local == 'r':
            summary['run_count'] += 1
        elif local == 'tbl':
            summary['table_count'] += 1
        elif local == 'hyperlink':
            summary['hyperlink_count'] += 1
        elif local == 'drawing':
            summary['drawing_count'] += 1
        elif local == 'numPr':
            summary['numPr_presence'] += 1
        elif local == 'pStyle':
            summary['pStyle_counts'][el.get(val_attr, '')] += 1
        elif local == 'rStyle':
            summary['rStyle_counts'][el.get(val_attr, '')] += 1
        elif local in _SUMMARY_RUN_FLAGS:
            summary['rPr_flags'][local] += 1
    return summary


# ---------------------------------------------------------------------------
# External tool plumbing
# ---------------------------------------------------------------------------

def pandoc_docx_to_md(docx: Path, out_md: Path, media_dir: Path) -> None:
    subprocess.run(
        [
            'pandoc', '-f', 'docx', '-t', 'gfm',
            f'--extract-media={media_dir}',
            '-o', str(out_md), str(docx),
        ],
        check=True, capture_output=True,
    )


def build_via_docxsphinx(md_path: Path, work_dir: Path) -> Path:
    src = work_dir / 'source'
    build = work_dir / 'build'
    src.mkdir(parents=True, exist_ok=True)
    (src / 'conf.py').write_text(_CONF_PY)
    shutil.copy(md_path, src / 'index.md')
    media_src = md_path.parent / 'media'
    if media_src.exists():
        shutil.copytree(media_src, src / 'media', dirs_exist_ok=True)
    subprocess.run(
        ['sphinx-build', '-b', 'docx', '-q', str(src), str(build)],
        check=True, capture_output=True,
    )
    outputs = list(build.glob('*.docx'))
    if not outputs:
        raise RuntimeError(f'no .docx produced in {build}')
    return outputs[0]


# ---------------------------------------------------------------------------
# Report rendering
# ---------------------------------------------------------------------------

def _counter_diff_table(
    a: Counter, b: Counter, *, top: int | None = None,
) -> str:
    keys = sorted(set(a) | set(b), key=lambda k: -abs(b.get(k, 0) - a.get(k, 0)))
    if top is not None:
        keys = keys[:top]
    if not keys:
        return '_no data_'
    lines = ['| name | original | roundtrip | Δ | note |',
             '|---|---:|---:|---:|---|']
    for k in keys:
        orig = a.get(k, 0)
        rtrip = b.get(k, 0)
        if orig and not rtrip:
            note = 'original-only'
        elif rtrip and not orig:
            note = 'docxsphinx-only'
        else:
            note = ''
        lines.append(f'| `{k}` | {orig} | {rtrip} | {rtrip - orig:+d} | {note} |')
    return '\n'.join(lines)


def render_per_doc_report(name: str, orig: dict, rtrip: dict) -> str:
    lines = [
        f'# Roundtrip report — `{name}`',
        '',
        'Comparison of the original Word document against the `.docx` '
        'produced by running its pandoc-converted Markdown through '
        'docxsphinx\'s forward path.',
        '',
        '## Structural counts',
        '',
        '| Metric | Original | Roundtrip | Δ |',
        '|---|---:|---:|---:|',
    ]
    for key in ('paragraph_count', 'run_count', 'table_count',
                'hyperlink_count', 'drawing_count', 'numPr_presence'):
        lines.append(
            f'| {key} | {orig[key]} | {rtrip[key]} | {rtrip[key] - orig[key]:+d} |'
        )
    lines += [
        '',
        '## Paragraph styles',
        '',
        _counter_diff_table(orig['pStyle_counts'], rtrip['pStyle_counts']),
        '',
        '## Run styles',
        '',
        _counter_diff_table(orig['rStyle_counts'], rtrip['rStyle_counts']),
        '',
        '## Run-property flags',
        '',
        _counter_diff_table(orig['rPr_flags'], rtrip['rPr_flags']),
        '',
        '## Element tag distribution (top 20 by absolute Δ)',
        '',
        _counter_diff_table(orig['element_tags'], rtrip['element_tags'], top=20),
    ]
    return '\n'.join(lines) + '\n'


def _aggregate(summaries: list[dict]) -> dict:
    keys = ('pStyle_counts', 'rStyle_counts', 'rPr_flags', 'element_tags')
    out = {k: Counter() for k in keys}
    for s in summaries:
        for k in keys:
            out[k].update(s[k])
    return out


def render_aggregate_report(
    per_doc: list[tuple[str, dict, dict]],
) -> str:
    agg_orig = _aggregate([o for _, o, _ in per_doc])
    agg_rtrip = _aggregate([r for _, _, r in per_doc])

    lines = [
        '# Aggregate roundtrip findings',
        '',
        f'Corpus size: **{len(per_doc)} document(s)**.',
        '',
        '## Paragraph styles — patterns in originals but missing from docxsphinx',
        '',
    ]
    orig_only_ps = {
        k: v for k, v in agg_orig['pStyle_counts'].items()
        if k not in agg_rtrip['pStyle_counts']
    }
    if orig_only_ps:
        for style, count in sorted(orig_only_ps.items(), key=lambda p: -p[1]):
            lines.append(f'- `{style}` (seen {count}× in originals)')
    else:
        lines.append('_(none)_')

    lines += [
        '',
        '## Paragraph styles — emitted by docxsphinx but not in originals',
        '',
    ]
    rtrip_only_ps = {
        k: v for k, v in agg_rtrip['pStyle_counts'].items()
        if k not in agg_orig['pStyle_counts']
    }
    if rtrip_only_ps:
        for style, count in sorted(rtrip_only_ps.items(), key=lambda p: -p[1]):
            lines.append(f'- `{style}` (emitted {count}×)')
    else:
        lines.append('_(none)_')

    lines += [
        '',
        '## Run styles — patterns in originals but missing from docxsphinx',
        '',
    ]
    orig_only_rs = {
        k: v for k, v in agg_orig['rStyle_counts'].items()
        if k not in agg_rtrip['rStyle_counts']
    }
    if orig_only_rs:
        for style, count in sorted(orig_only_rs.items(), key=lambda p: -p[1]):
            lines.append(f'- `{style}` (seen {count}× in originals)')
    else:
        lines.append('_(none)_')

    lines += [
        '',
        '## Element tags only emitted by one side',
        '',
        '### Originals only',
        '',
    ]
    orig_only_tags = set(agg_orig['element_tags']) - set(agg_rtrip['element_tags'])
    if orig_only_tags:
        for t in sorted(orig_only_tags):
            lines.append(f'- `w:{t}` ({agg_orig["element_tags"][t]}×)')
    else:
        lines.append('_(none)_')

    lines += [
        '',
        '### docxsphinx only',
        '',
    ]
    rtrip_only_tags = set(agg_rtrip['element_tags']) - set(agg_orig['element_tags'])
    if rtrip_only_tags:
        for t in sorted(rtrip_only_tags):
            lines.append(f'- `w:{t}` ({agg_rtrip["element_tags"][t]}×)')
    else:
        lines.append('_(none)_')

    lines += [
        '',
        '## Full paragraph-style distribution across the corpus',
        '',
        _counter_diff_table(agg_orig['pStyle_counts'], agg_rtrip['pStyle_counts']),
        '',
        '## Full run-style distribution across the corpus',
        '',
        _counter_diff_table(agg_orig['rStyle_counts'], agg_rtrip['rStyle_counts']),
        '',
        '## Full element tag distribution (top 30 by absolute Δ)',
        '',
        _counter_diff_table(agg_orig['element_tags'], agg_rtrip['element_tags'], top=30),
    ]
    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        'input_dir', type=Path,
        help='directory containing .docx files to analyse',
    )
    parser.add_argument(
        'output_dir', type=Path,
        help='directory to write per-doc and aggregate reports into',
    )
    args = parser.parse_args(argv)

    if not args.input_dir.is_dir():
        parser.error(f'input directory does not exist: {args.input_dir}')
    args.output_dir.mkdir(parents=True, exist_ok=True)

    docs = sorted(args.input_dir.glob('*.docx'))
    if not docs:
        print(
            f'no .docx files found in {args.input_dir}',
            file=sys.stderr,
        )
        return 1

    per_doc: list[tuple[str, dict, dict]] = []
    for doc in docs:
        print(f'processing: {doc.name}', flush=True)
        with tempfile.TemporaryDirectory() as tmp:
            work = Path(tmp)
            md = work / 'index.md'
            media = work / 'media'
            try:
                pandoc_docx_to_md(doc, md, media)
            except subprocess.CalledProcessError as exc:
                err = exc.stderr.decode(errors='replace') if exc.stderr else str(exc)
                print(f'  pandoc failed: {err}', file=sys.stderr)
                continue
            try:
                rtrip_docx = build_via_docxsphinx(md, work)
            except subprocess.CalledProcessError as exc:
                err = exc.stderr.decode(errors='replace') if exc.stderr else str(exc)
                print(f'  docxsphinx build failed:\n{err}', file=sys.stderr)
                continue
            orig = summarise_tree(extract_document_xml(doc))
            rtrip = summarise_tree(extract_document_xml(rtrip_docx))
            report = render_per_doc_report(doc.name, orig, rtrip)
            (args.output_dir / f'{doc.stem}.report.md').write_text(report)
            per_doc.append((doc.name, orig, rtrip))

    if not per_doc:
        print('no documents successfully processed', file=sys.stderr)
        return 1

    aggregate = render_aggregate_report(per_doc)
    (args.output_dir / 'aggregate.report.md').write_text(aggregate)
    print(
        f'\nwrote {len(per_doc)} per-doc report(s) + aggregate.report.md '
        f'to {args.output_dir}',
    )
    return 0


if __name__ == '__main__':
    sys.exit(main())
